---
- name: 'Test for CVE-2015-0235 (GHOST) vulnerability'
  hosts: all
  sudo: True

  tasks:
    - name: check for gcc
      stat:
        path: /usr/bin/gcc
      register: gcc
      failed_when: not gcc.stat.exists

    - name: copy over GHOST.c
      copy:
        dest: /tmp/GHOST.c
        src: files/GHOST.c
        owner: root
        group: root
        mode: 0644

    - name: compile GHOST
      command: gcc /tmp/GHOST.c -o /tmp/GHOST

    - name: run GHOST vulnerability checker
      command: /tmp/GHOST
      register: GHOST

    - name: cleanup GHOST files
      file:
        name: /tmp/{{ item }}
        state: absent
      with_items:
        - GHOST.c
        - GHOST

    - debug:
        msg: "This machine is {{ GHOST.stdout }}."
      failed_when: "GHOST.stdout == 'vulnerable'"
